<a href="https://colab.research.google.com/github/suyogy1-bot/Numpy/blob/main/Class1file.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Using NumPy**

Once you've installed NumPy you can import it as a library:

In [ ]:
import numpy as np
l = [10,20,30,40,50] # 1D Array
array = np.array(l)
array

array([10, 20, 30, 40, 50])

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

Lets create a matrix using list

In [ ]:
a = [
    [ 1,  2,  3,  4],
    [ 5,  6,  7,  8],
    [ 9, 10, 11, 12]]

matrix = np.array(a)
matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## Built-in Methods

there are lots of build in methods to create an array lets create some and see

np.zeros(), np.ones(), np.full()

np.arange(), np.linspace()

np.eye()

In [ ]:
np.zeros(4) # for 1D

array([0., 0., 0., 0.])

In [ ]:
# np.zeros for matrix

np.zeros([3,4]) # 3 rows and 4 columns

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones(4)

array([1., 1., 1., 1.])

In [ ]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.full(5,1)

array([1, 1, 1, 1, 1])

In [ ]:
np.full(5,'a')

array(['a', 'a', 'a', 'a', 'a'], dtype='<U1')

In [ ]:
np.full([3,4],7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [ ]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.linspace(0,1,5) # Start = 0, stop = 1, value = 5 , all values are equally distributed

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
np.random.rand(2,3) # rows, columns

array([[0.47644976, 0.63633938, 0.17072892],
       [0.67372581, 0.48503599, 0.64236417]])

In [ ]:
np.random.randint(1,20,[3,4]) # start, stop, [rows, columns]

array([[ 7,  2,  9, 10],
       [14,  2, 11, 10],
       [ 3,  7, 10, 12]])

arange → step-based values

linspace → fixed number of values

eye → identity matrix

rand → random floats (0–1)

randint → random integers in a range

randn → random values from bell curve distribution