<a href="https://colab.research.google.com/github/suyogy1-bot/Numpy/blob/main/class2file.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##1. Attributes of an Array

Introduce attributes that describe the array.

Attributes: .shape, .ndim, .size, .dtype.

In [10]:
import numpy as np

arr = [1,2,3],[4,5,6],[7,8,9]
arr = np.array(arr)

brr = [[1,2,3],[4,5,6],[7,8,9]]
brr = np.array(brr)

crr = [[[1,2,3],[4,5,6],[7,8,9]]]
crr = np.array(brr)

print(arr.shape)
print(arr.ndim)
print(brr.ndim)
print(crr.ndim)

#.size -> Number of elements
print(arr.size)

#.dtypes -> data type inside your array
drr = [1.0,2.0,3.0,5,"hello"]
drr = np.array(drr)
print(drr.dtype)

(3, 3)
2
2
2
9
<U32


##Indexing and Slicing
Now we have Indexing and slicing aswell and for that we are going to see 1d and 2d indexing lets start with **1D indexing** and it is similar to list.

In [11]:
arr = np.array([10,20,30,40,50])

# 1D array indexing and slicing = List

print(arr[0])
print(arr[1])
print(arr[2])
print(arr[3])
print(arr[4])
print(arr[-1])
print(arr[-2])
print(arr[-3])
print(arr[-4])
print(arr[-5])

10
20
30
40
50
50
40
30
20
10


Now lets see the 2D indexing aswell

In [13]:
# 2D indexing -> matrix -> row, column

arr = np.array([[10,20,30,40,50],[60,70,80,90,100]])

print(arr[0,0])
print(arr[0,1])

10
20


Now we can also do the slicing lets see the **slicing in 1D**

In [17]:
brr[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
brr[0:2, 0:2] # Rows from 0,1 and columns from 0,1

array([[1, 2],
       [4, 5]])

In [21]:
brr[1:3, 1:3]

array([[5, 6],
       [8, 9]])

In [26]:
brr[1:, 1:2]

array([[5],
       [8]])

There is one more thing known as **Boolean indexing**

In [29]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

In [31]:
print(arr > 5)

[False False False False False  True  True  True  True  True]


In [30]:
arr[arr > 10]

array([], dtype=int64)

## Reshaping the Array

you can also reshape the Array as you like but be accurate about the dimensions

## Flattening of an array

you can convert the 2D array to 1D using the Flattening Function