
# NumPy Assignment — 1

## Topics Covered
- Import NumPy
- NumPy Arrays
- zeros()
- ones()
- full()
- arange()
- linspace()
- eye()
- Random Arrays

### Instructions
- Use NumPy in every question.
- Follow the concepts taught in class.
- Write code in the blank code cells.



# Q1. Create a NumPy Array

## Problem Statement
Create a NumPy array using the list:
```python
[10, 20, 30, 40, 50]
```

## Sample Output
```python
[10 20 30 40 50]
```


In [ ]:
# Write your code here


# Q2. Create a 3×3 Matrix

## Problem Statement
Convert the following list into a NumPy array:
```python
[[1,2,3],
 [4,5,6],
 [7,8,9]]
```

## Sample Output
```python
[[1 2 3]
 [4 5 6]
 [7 8 9]]
```


In [ ]:
# Write your code here


# Q3. Create an Array of Zeros

## Problem Statement
Create an array containing 5 zeros using NumPy.

## Sample Output
```python
[0. 0. 0. 0. 0.]
```


In [ ]:
# Write your code here


# Q4. Create a 2×4 Zero Matrix

## Problem Statement
Create a matrix of zeros having 2 rows and 4 columns.

## Sample Output
```python
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
```


In [ ]:
# Write your code here


# Q5. Create an Array of Ones

## Problem Statement
Create an array containing 6 ones.

## Sample Output
```python
[1. 1. 1. 1. 1. 1.]
```


In [ ]:
# Write your code here


# Q6. Create a Matrix Using full()

## Problem Statement
Create a 3×3 matrix filled with the value 9.

## Sample Output
```python
[[9 9 9]
 [9 9 9]
 [9 9 9]]
```


In [ ]:
# Write your code here


# Q7. Create Numbers Using arange()

## Problem Statement
Create an array of even numbers from 0 to 20 using arange().

## Sample Output
```python
[ 0  2  4  6  8 10 12 14 16 18]
```


In [ ]:
# Write your code here


# Q8. Create Values Using linspace()

## Problem Statement
Create 6 equally spaced values between 0 and 1.

## Sample Output
```python
[0.  0.2 0.4 0.6 0.8 1. ]
```


In [ ]:
# Write your code here


# Q9. Create an Identity Matrix

## Problem Statement
Create a 5×5 identity matrix using NumPy.

## Sample Output
```python
[[1. 0. 0. 0. 0.]
 ...
]
```


In [ ]:
# Write your code here


# Q10. Create a Random Integer Matrix

## Problem Statement
Create a 3×3 matrix containing random integers between 1 and 20.

## Sample Output
```python
[[12  5 18]
 [ 3 15  9]
 [11  7 20]]
```


In [ ]:
# Write your code here