
# Final NumPy Assignment
# Inputs khud se create karna hai



# Q1. Array Creation and Attributes

## Problem Statement
Create array [10,20,30,40,50] and print shape, ndim, size and dtype.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [3]:
import numpy as np

arr = np.arange(0,60,10)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

1
6
int64



# Q2. Matrix Creation

## Problem Statement
Create a 3x3 NumPy matrix and print it.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [9]:
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]



# Q3. Indexing Practice

## Problem Statement
Print first, third and last element from an array.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [11]:
arr = np.arange(5)
print(arr[0])
print(arr[2])
print(arr[-1])

0
2
4



# Q4. Slicing Practice

## Problem Statement
Print elements from index 2 to 5.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [13]:
print(arr[2:5])

[2 3 4]



# Q5. Fancy Indexing

## Problem Statement
Print selected elements using fancy indexing.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [17]:
new = arr[2:5]
print(new)

[2 3 4]



# Q6. Conditional Selection

## Problem Statement
Print values greater than 15.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [19]:
arr = np.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [22]:
new = arr[arr > 15]
new

array([16, 17, 18, 19])


# Q7. Broadcasting

## Problem Statement
Add 10 to every element of an array.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [24]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [26]:
new

array([16, 17, 18, 19])

In [28]:
sum = new + 10
sum

array([26, 27, 28, 29])


# Q8. Aggregate Functions

## Problem Statement
Print sum, mean, max and min.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [30]:
print(new.sum)
print(new.mean)
print(new.max)
print(new.min)

<built-in method sum of numpy.ndarray object at 0x106b2f7b0>
<built-in method mean of numpy.ndarray object at 0x106b2f7b0>
<built-in method max of numpy.ndarray object at 0x106b2f7b0>
<built-in method min of numpy.ndarray object at 0x106b2f7b0>


In [34]:
print(new.sum())
print(new.mean())
print(new.max())
print(new.min())

70
17.5
19
16



# Q9. Sorting

## Problem Statement
Sort an unsorted NumPy array.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [44]:
arr = np.array([21,12,1,30,3,50,33])
arr.sort()
arr

array([ 1,  3, 12, 21, 30, 33, 50])

In [48]:
arr = np.array([21,12,1,30,3,50,33])
new = np.sort(arr)
print(new)
print(arr)

[ 1  3 12 21 30 33 50]
[21 12  1 30  3 50 33]



# Q10. Concatenation and Stacking

## Problem Statement
Perform concatenate and vstack on two arrays.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [84]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a + b)
print(np.hstack([a,b]))
print(np.vstack([a,b]))

[5 7 9]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [52]:
import numpy as np

a = np.array([3, 1, 4, 1, 5])
sorted_a = np.sort(a)      # [1, 1, 3, 4, 5]
a.sort()                   # a is now [1, 1, 3, 4, 5]


In [54]:
b = np.array([[3, 1, 2],
              [9, 7, 8]])

np.sort(b, axis=0)
# array([[3, 1, 2],
#        [9, 7, 8]])  # columns sorted independently

np.sort(b, axis=1)
# array([[1, 2, 3],
#        [7, 8, 9]])  # rows sorted independently


array([[1, 2, 3],
       [7, 8, 9]])

In [66]:
b.sort(axis=1) # sorts rows of b in place
b

array([[1, 2, 3],
       [7, 8, 9]])

In [58]:
a = np.array([30, 10, 20])
idx = np.argsort(a)    # [1, 2, 0]
sorted_a = a[idx]      # [10, 20, 30]


In [68]:
b = np.array([[3, 1, 2],
              [9, 7, 8]])

idx_rows = np.argsort(b, axis=1)  # indices to sort each row
idx_rows

array([[1, 2, 0],
       [1, 2, 0]])

In [70]:
data = np.array([[101, 50],
                 [102, 20],
                 [103, 80]])

# sort by column 1 (scores)
order = np.argsort(data[:, 1])
sorted_data = data[order]
sorted_data

array([[102,  20],
       [101,  50],
       [103,  80]])

In [76]:
order_new = np.argsort(data)
order_new

array([[1, 0],
       [1, 0],
       [1, 0]])

In [80]:
order_col = np.sort(data, axis=0)
order_col

array([[101,  20],
       [102,  50],
       [103,  80]])

In [82]:
order_row = np.sort(data, axis=1)
order_row

array([[ 50, 101],
       [ 20, 102],
       [ 80, 103]])