<a href="https://colab.research.google.com/github/suyogy1-bot/Numpy/blob/main/class3file.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Numpy array operations

Lets first see how arrays behave like “vectors/matrices” when operations happen element-wise.

In [3]:
import numpy as np
a = np.array([10,20,30,40])
b = np.arange(1,5)

print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a ** b)

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]
[     10     400   27000 2560000]


In [4]:
a = np.array([[10,20,30],
              [40,50,60]])

b = np.array([10,20,30])

print(a + b)

[[20 40 60]
 [50 70 90]]


In [5]:
a = np.array([[10,20,30],
              [40,50,60]])

b = np.array([10])

print(a + b)

[[20 30 40]
 [50 60 70]]


These things are already different from List and if we talk about one more special power it is **Broadcasting**

Even these things work with different shaped array the calculations will happen on every row. but dimensions must match

#Aggregate Functions

These functions are used to calculate the statistics on arrays.

In [7]:
# Basic Statistical operations perform
# 1. Sum
# 2. Mean
# 3. Max
# 4. Min
# 5. Standard Deviation
# 6. Variance

In [9]:
arr = np.array([4,78,21,34,100,56])

print(f"Sum is: {np.sum(arr)}")
print(f"Mean(Average) is: {np.mean(arr)}")
print(f"Max is : {np.max(arr)}")
print(f"Min is: {np.min(arr)}")
print(f"Standard Deviation: {np.std(arr)}")
print(f"Variance: {np.var(arr)}")

Sum is: 293
Mean(Average) is: 48.833333333333336
Max is : 100
Min is: 4
Standard Deviation: 32.97684372741306
Variance: 1087.4722222222224


You can also do the axis based operations row-Wise and Colum-wise

In [12]:
data = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

print(f"Sum of all: {np.sum(data)}")
print(f"Sum of columns: {np.sum(data, axis=0)}")
print(f"Sum of rows: {np.sum(data, axis=1)}")

Sum of all: 45
Sum of columns: [12 15 18]
Sum of rows: [ 6 15 24]
