<a href="https://colab.research.google.com/github/suyogy1-bot/Numpy/blob/main/class4file.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Fancy Indexing
you can Pick elements from specific positions using a list/array of indices.

In [ ]:
import numpy as np

arr = np.arange(0,70,10)
arr

array([ 0, 10, 20, 30, 40, 50, 60])

In [ ]:
arr[[0,2,4]]

array([ 0, 20, 40])

In [ ]:
# Pick elements at position 1,0,5
indices = np.array([1,0,5])
arr[indices]

array([10,  0, 50])

You can do this fancy indexing in 2D Matrix aswell

In [3]:
import numpy as np
matrix = np.arange(1,13).reshape(3,4)
matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [10]:
print(matrix[[0,1],[1,2]])

[2 7]


In [13]:
print(matrix[[1,2,1],[0,2,3]])

[ 5 11  8]


In [1]:
[] # 1D array
[[],[]] # 2D array/Matrix

[[], []]

##Conditional Selection
Find values based on conditions or replace them.

In [16]:
arr = np.array([5,7,11,18,30])

# We will get the indices only
# which are greater than 10
np.where(arr > 10)

(array([2, 3, 4]),)

In [17]:
np.where(arr > 10, arr, 0) # replace in arr with 0

array([ 0,  0, 11, 18, 30])

In your line:

```python
np.where(arr > 10, arr, 0)

```

- ‎`condition` is ‎`arr > 10`

- ‎`x` is ‎`arr`

- ‎`y` is ‎`0`

The rule of ‎`np.where(condition, x, y)` is:

for each element → if ‎`condition` is True → take from ‎`x`, else → take from ‎`y`.

Your ‎`arr` is:

```python
arr = np.array([5, 7, 11, 18, 30])

```

Let’s see the condition ‎`arr > 10`:

- 5  > 10 → False → take from ‎`0` → 0

- 7  > 10 → False → take from ‎`0` → 0

- 11 > 10 → True  → take from ‎`arr` → 11

- 18 > 10 → True  → 18

- 30 > 10 → True  → 30



In [20]:
arr2 = np.array([23,25,30,50,100,75,80])

np.where(arr2 > 55, arr2, 0)

array([  0,   0,   0,   0, 100,  75,  80])

##Sorting & Ordering
np.sort() → returns sorted array

np.argsort() → returns indices of sorted order

In [22]:
arr = np.array([2, 10, 56, 1, 54])
np.sort(arr)

array([ 1,  2, 10, 54, 56])

In [23]:
np.argsort(arr)

array([3, 0, 1, 4, 2])

In [30]:
# Matrix sort
# 1. Row wise sort (axis = 1)
# 2. Column wise sort (axis = 0)

In [33]:
matrix = np.array([[4,3,12],[14,15,10]])
np.sort(matrix, axis = 1)

array([[ 3,  4, 12],
       [10, 14, 15]])

In [34]:
np.sort(matrix, axis = 0)

array([[ 4,  3, 10],
       [14, 15, 12]])

In [35]:
np.sort(matrix)

array([[ 3,  4, 12],
       [10, 14, 15]])

##Concatenation & Stacking

In [24]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.concatenate([a,b])

array([1, 2, 3, 4, 5, 6])

Vertical & Horizontal Stacking

In [25]:
np.vstack([a,b])

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
np.hstack([a,b])

array([1, 2, 3, 4, 5, 6])

In [27]:
a = np.array([1,2,3])
b = np.array([4,5,6,7])

In [29]:
np.hstack([a,b])

array([1, 2, 3, 4, 5, 6, 7])

In [36]:
A  = np.array([[1,2],[4,5]])
B  = np.array([[6,7],[8,9]])

In [37]:
np.vstack([A,B])

array([[1, 2],
       [4, 5],
       [6, 7],
       [8, 9]])

In [38]:
np.hstack([A,B])

array([[1, 2, 6, 7],
       [4, 5, 8, 9]])