
# NumPy Assignment — 1

## Topics Covered
- Import NumPy
- NumPy Arrays
- zeros()
- ones()
- full()
- arange()
- linspace()
- eye()
- Random Arrays

### Instructions
- Use NumPy in every question.
- Follow the concepts taught in class.
- Write code in the blank code cells.



# Q1. Create a NumPy Array

## Problem Statement
Create a NumPy array using the list:
```python
[10, 20, 30, 40, 50]
```

## Sample Output
```python
[10 20 30 40 50]
```


In [3]:
import numpy as np

In [5]:
a = np.array([10,20,30,40,50])
a

array([10, 20, 30, 40, 50])


# Q2. Create a 3×3 Matrix

## Problem Statement
Convert the following list into a NumPy array:
```python
[[1,2,3],
 [4,5,6],
 [7,8,9]]
```

## Sample Output
```python
[[1 2 3]
 [4 5 6]
 [7 8 9]]
```


In [9]:
a = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])


# Q3. Create an Array of Zeros

## Problem Statement
Create an array containing 5 zeros using NumPy.

## Sample Output
```python
[0. 0. 0. 0. 0.]
```


In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])


# Q4. Create a 2×4 Zero Matrix

## Problem Statement
Create a matrix of zeros having 2 rows and 4 columns.

## Sample Output
```python
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
```


In [15]:
np.zeros([2,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])


# Q5. Create an Array of Ones

## Problem Statement
Create an array containing 6 ones.

## Sample Output
```python
[1. 1. 1. 1. 1. 1.]
```


In [17]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])


# Q6. Create a Matrix Using full()

## Problem Statement
Create a 3×3 matrix filled with the value 9.

## Sample Output
```python
[[9 9 9]
 [9 9 9]
 [9 9 9]]
```


In [25]:
print(np.full([3,3],9))

[[9 9 9]
 [9 9 9]
 [9 9 9]]



# Q7. Create Numbers Using arange()

## Problem Statement
Create an array of even numbers from 0 to 20 using arange().

## Sample Output
```python
[ 0  2  4  6  8 10 12 14 16 18]
```


In [29]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])


# Q8. Create Values Using linspace()

## Problem Statement
Create 6 equally spaced values between 0 and 1.

## Sample Output
```python
[0.  0.2 0.4 0.6 0.8 1. ]
```


In [31]:
np.linspace(0,1,6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])


# Q9. Create an Identity Matrix

## Problem Statement
Create a 5×5 identity matrix using NumPy.

## Sample Output
```python
[[1. 0. 0. 0. 0.]
 ...
]
```


In [37]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])


# Q10. Create a Random Integer Matrix

## Problem Statement
Create a 3×3 matrix containing random integers between 1 and 20.

## Sample Output
```python
[[12  5 18]
 [ 3 15  9]
 [11  7 20]]
```


In [40]:
np.random.randint(1,20,[3,3])

array([[15, 13, 17],
       [ 2, 19,  7],
       [ 1,  1, 18]])

In [42]:
!git status


On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   numpy_assignment_1.ipynb

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	.ipynb_checkpoints/

no changes added to commit (use "git add" and/or "git commit -a")


In [44]:
!git add numpy_assignment_1.ipynb

In [46]:
!git commit -m "Update notebook"

[main 63a52d3] Update notebook
 1 file changed, 216 insertions(+), 30 deletions(-)


In [48]:
!git push origin main

Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 8 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 1.53 KiB | 1.53 MiB/s, done.
Total 3 (delta 1), reused 0 (delta 0), pack-reused 0 (from 0)
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
To https://github.com/suyogy1-bot/Numpy.git
   a961ea9..63a52d3  main -> main
