
# NumPy Assignment — Fancy Indexing, Conditional Selection, Sorting & Stacking

## Level: Basic

### Topics Covered
- Fancy Indexing
- Conditional Selection
- np.sort()
- np.argsort()
- Concatenation
- Vertical Stacking
- Horizontal Stacking

### Instructions
- Use NumPy in every question.
- Write your solution in the code cell below each question.
- Print the required output.



# Q1. Fancy Indexing (1D Array)

## Problem Statement
Create the array:

```python
[10, 20, 30, 40, 50, 60]
```

Using fancy indexing, print:
- 10
- 30
- 60

## Sample Output
```python
[10 30 60]
```


In [15]:
import numpy as np

arr = np.array([10,20,30,40,50,60])
result = arr[[0, 2, -1]]
print(result)

[10 30 60]



# Q2. Fancy Indexing (1D Array)

## Problem Statement
Create the array:

```python
[5, 15, 25, 35, 45]
```

Using fancy indexing, print:
- 15
- 45

## Sample Output
```python
[15 45]
```


In [17]:
arr = np.array([5, 15, 25, 35, 45])
result = arr[[1,-1]]
print(result)

[15 45]



# Q3. Fancy Indexing (2D Array)

## Problem Statement
Create the matrix:

```python
[[10,20,30],
 [40,50,60],
 [70,80,90]]
```

Using fancy indexing, print:
- 10
- 50
- 90

## Sample Output
```python
[10 50 90]
```


In [27]:
arr = np.array([[10,20,30],
                [40,50,60],
                [70,80,90]])

result = arr[[0,1,2],[0,1,2]]
print(result)

[10 50 90]



# Q4. Conditional Selection

## Problem Statement
Create the array:

```python
[5, 12, 18, 25, 30, 7]
```

Print only values greater than 15.

## Sample Output
```python
[18 25 30]
```


In [29]:
arr = np.array([5, 12, 18, 25, 30, 7])

result = arr[arr > 15]
print(result)

[18 25 30]



# Q5. Conditional Selection

## Problem Statement
Create the array:

```python
[2, 4, 7, 10, 13, 16]
```

Print only even numbers.

## Sample Output
```python
[ 2  4 10 16]
```


In [31]:
arr = np.array([2, 4, 7, 10, 13, 16])

result = arr[arr % 2 == 0]
print(result)

[ 2  4 10 16]



# Q6. Sorting an Array

## Problem Statement
Create the array:

```python
[25, 10, 40, 5, 30]
```

Sort the array using `np.sort()`.

## Sample Output
```python
[ 5 10 25 30 40]
```


In [33]:
arr = np.array([25, 10, 40, 5, 30])

result = np.sort(arr)
print(result)

[ 5 10 25 30 40]



# Q7. Find Sorted Indices

## Problem Statement
Create the array:

```python
[50, 20, 70, 10]
```

Use `np.argsort()` to find the indices of sorted elements.

## Sample Output
```python
[3 1 0 2]
```


In [35]:
arr = np.array([50, 20, 70, 10])

result = np.argsort(arr)
print(result)

[3 1 0 2]



# Q8. Concatenate Arrays

## Problem Statement
Create two arrays:

```python
arr1 = [1,2,3]
arr2 = [4,5,6]
```

Concatenate both arrays.

## Sample Output
```python
[1 2 3 4 5 6]
```


In [41]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

result = np.concatenate([arr1, arr2])
print(result)

[1 2 3 4 5 6]



# Q9. Vertical Stacking

## Problem Statement
Create two arrays:

```python
[1,2,3]
[4,5,6]
```

Combine them using vertical stacking.

## Sample Output
```python
[[1 2 3]
 [4 5 6]]
```


In [45]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

print(np.vstack([arr1,arr2]))

[[1 2 3]
 [4 5 6]]



# Q10. Horizontal Stacking

## Problem Statement
Create two arrays:

```python
[10,20,30]
[40,50,60]
```

Combine them using horizontal stacking.

## Sample Output
```python
[10 20 30 40 50 60]
```


In [47]:
arr1 = np.array([10,20,30])
arr2 = np.array([40,50,60])

print(np.hstack([arr1,arr2]))

[10 20 30 40 50 60]
